"""Geo in Building

Revision ID: 3837d59e87eb
Revises: 9da5b6003442
Create Date: 2025-11-01 21:10:13.111997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3837d59e87eb'
down_revision: Union[str, Sequence[str], None] = '9da5b6003442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')

    # 1. Добавляем колонку как NULLABLE (без NOT NULL)
    op.add_column('buildings', sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=True), nullable=True))
    
    # 2. Заполняем существующие данными из latitude и longitude
    op.execute("""
        UPDATE buildings 
        SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
        WHERE geom IS NULL
    """)
    
    # 3. Проверяем что нет NULL значений
    op.execute("""
        DELETE FROM buildings WHERE geom IS NULL
    """)
    
    # 4. Делаем колонку NOT NULL
    op.alter_column('buildings', 'geom', nullable=False)
    
    op.create_index('idx_buildings_geom', 'buildings', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buildings_geom', table_name='buildings', postgresql_using='gist')
    op.drop_column('buildings', 'geom')
    # ### end Alembic commands ###
