"""cascade delete in organisation-activity table

Revision ID: 9da5b6003442
Revises: 784c126e80ca
Create Date: 2025-10-27 15:52:58.217460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da5b6003442'
down_revision: Union[str, Sequence[str], None] = '784c126e80ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organization_activity_rels_organization_id_fkey'), 'organization_activity_rels', type_='foreignkey')
    op.drop_constraint(op.f('organization_activity_rels_activity_id_fkey'), 'organization_activity_rels', type_='foreignkey')
    op.create_foreign_key(None, 'organization_activity_rels', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_activity_rels', 'activitys', ['activity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_activity_rels', type_='foreignkey')
    op.drop_constraint(None, 'organization_activity_rels', type_='foreignkey')
    op.create_foreign_key(op.f('organization_activity_rels_activity_id_fkey'), 'organization_activity_rels', 'activitys', ['activity_id'], ['id'])
    op.create_foreign_key(op.f('organization_activity_rels_organization_id_fkey'), 'organization_activity_rels', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
